const products = [
  {
    id: 1,
    title: "14k Yellow-Gold Earring",
    heart: "../../assets/icons/favourite.svg",
    price: "12,000",
    imageSrc: "../../assets/Golden.svg",
    rating: 4,
    label: "New Arrival",
  },
  {
    id: 2,
    title: "Double-Band Cork Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "18,000",
    imageSrc: "../../assets/Corkring.svg",
    rating: 4,
    label: "Bestseller",
  },
  {
    id: 3,
    title: "Wedding Earrings",
    heart: "../../assets/icons/favourite.svg",
    price: "100,000",
    imageSrc: "../../assets/wedding.svg",
    rating: 4,
    label: "Luxury",
  },
  {
    id: 4,
    title: "Rail Rings",
    heart: "../../assets/icons/favourite.svg",
    price: "1200",
    imageSrc: "../../assets/RailRing.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 5,
    title: "Pandora Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "18,000",
    imageSrc: "../../assets/Pandora.svg",
    rating: 4,
    label: " ",
  },
  {
    id: 6,
    title: "Knotted Heart Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "18,000",
    imageSrc: "../../assets/Knot.svg",
    rating: 4,
    label: " ",
  },
  {
    id: 7,
    title: "Minimal Love Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "100",
    imageSrc: "../../assets/Minimal.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 8,
    title: "Knotted Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/Knotted.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 9,
    title: "Eric Suavage Pendant",
    heart: "../../assets/icons/favourite.svg",
    price: "200",
    imageSrc: "../../assets/Pendant.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 10,
    title: "Minimalist Love Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/LoveRing.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 11,
    title: "Jil Sander Earrings",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/Earring.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 12,
    title: "Chunky Ring",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/Chunky.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 13,
    title: "White & Gold Pendant",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/WHite.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 14,
    title: "Cupid Pendant",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/Pendant.svg",
    rating: 4,
    label: "Body",
  },
  {
    id: 15,
    title: "Ross Simons Accessories",
    heart: "../../assets/icons/favourite.svg",
    price: "1300",
    imageSrc: "../../assets/Ross.svg",
    rating: 4,
    label: "Body",
  },
];

export default products;
